title: Zakaria Laabsi # your name (or website title) here
logo: "/images/idlogo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br> Zakaria Laabsi, Master's student in Mathematics applied <br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/zakaria-laabsi-125b08206/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
